################
# Jenkins user #
################
---
- name: Check localhost for authorized key for jenkins user
  delegate_to: localhost
  become: false
  stat:
    path: "{{ Jenkins_User_SSHKey }}"
  register: pubkey

- name: Set authorized key for jenkins user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '{{ Jenkins_User_SSHKey }}') }}"
  when: pubkey is defined and pubkey.stat.exists
  register: jenkins_pubkey
  tags: jenkins_user
